### ISSUE TITLE
Make Responsive

### ISSUE THREAD

**Issue by mitrerogelio** [SaboyaTech/thf-construction#6]
The hero on desktop looks good, but it needs to be responsive.

- [x] Navbar
- [x] Hero Section

**Comment by SaboyaTech** [comment]
- [ ] Navbar
- [ ] Hero Section
- [ ] Our Services

**Comment by saboyadev** [comment]
https://www.loom.com/share/9ba72ad9fccc4e5aa605f3cfa79c90c9?sid=a8da9a63-c7f8-4467-b6ad-bf2b9d485572
![Screenshot 2024-03-17 at 6 48 32 PM](https://github.com/SaboyaTech/thf-construction/assets/16430662/202ba04f-1704-4b84-adfa-13fa3656ee54)
